server:
  port: 9002

eureka:
  client:
    register-with-eureka: true  # 服务注册开关
    fetch-registry: true  # 服务发现开关
    service-url:  # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone:  http://localhost:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  # 访问路径可以显示IP地址

spring:
  application:
    name: sso-client2
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      client-id: client2 # 当前客户端id
      client-secret: JX-PWD # 客户端的密码
      user-authorization-uri: http://localhost:7001/auth/oauth/authorize #请求认证的地址，获取授权码地址
      access-token-uri: http://localhost:7001/auth/oauth/token # 请求令牌的地址
    resource:
      jwt:
        # 当用户授权之后会响应一个授权码，重定向到当前应用的 http://localhost:9001/login?code=xxx
        # 自动的会对 /login 去获取令牌，获取到令牌后会通过 key-uri 获取到的公钥进行解密然后本地身份认证和授权（Session）
        key-uri: http://localhost:7001/auth/oauth/token_key # 获取公钥